### ISSUE TITLE
Passwords and PATHS in files

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/PDS-Pipelines#1]
We have a number of deprecated passwords in these files.  We need to identify where these are in the source code for future removal.

## Acceptance Criteria

- [x] Response(s) to this issues with links to the locations where passwords or paths are in source.

**Comment by eabovre** [comment]
I found one here.

**Comment by eabovre** [comment]
and here

**Comment by eabovre** [comment]
Bob said that this is a password line, so I am just going to find these guys!

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/DIqueueing.py#L76

**Comment by jlaura** [comment]
:+1:

**Comment by eabovre** [comment]
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/PDS_DBsessions.py#L36

**Comment by eabovre** [comment]
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/PDS_DBsessions.py#L36

**Comment by eabovre** [comment]
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/ChecksumUpdateProcess.py#L43

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/ChecksumUpdateQueueing.py#L77

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/FindDI_Ready.py#L49

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/UPCqueueing.py#L67

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/DIprocess.py#L75

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/IngestProcess.py#L94

**Comment by eabovre** [comment]
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/PDS_DBsessions.py#L22

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/UPC_test.py#L19

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/UPC_test.py#L19

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/test_DBadd.py#L40

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/789fc1559774202b276812c437a0061fe351b7a6/bin/UPC_process.py#L71
