### ISSUE TITLE
Refactor error handling and hard-coded db adds in UPC_Process.py

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#10]
Find a way to more elegantly handle error scenarios and remove the "magic number" issue regarding typeid and value.

Relevant sections: 

https://github.com/AustinSanders/PDS-Pipelines/blob/e691a38df67068a00f70e9a3df54b1b95860d334/bin/UPC_process.py#L441-L463

https://github.com/AustinSanders/PDS-Pipelines/blob/e691a38df67068a00f70e9a3df54b1b95860d334/bin/UPC_process.py#L498-L528

**Comment by AustinSanders** [comment]
@USGSsakins @jlaura  The more I've looked into this one, the less terrible the hard-coding seems to be.  There are magic numbers here, but they're just populating the database with error codes when a process fails.  It's a little (or a lot) ugly, but is there anything that we can really do here?

**Comment by AustinSanders** [comment]
Also, some of the error handling logic here may be responsible for #58. We're explicitly inputting a footprint value of 361 -- not sure if that's part of the problem here, but it may be worth looking into.

**Comment by USGSsakins** [comment]
@AustinSanders we should do a lookup on the error keyword to get the typeid instead of hard coding magic numbers.
