### ISSUE TITLE
Replace shebang lines with /usr/bin/env to grab environment python

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#113]
Currently, all python scripts explicitly call a particular python interpreter `/usgs/apps/anaconda/bin/python`

The current method isn't flexible, and the new method will allow us to create an arbitrary conda environment that supports PDS-Pipelines.

**Comment by jlaura** [comment]
:+1:

**Comment by dpmayerUSGS** [comment]
Fixed in the heat of the moment by https://github.com/USGS-Astrogeology/PDS-Pipelines/commit/64d334fdc1d12c4a1702b142799d721653067155
