### ISSUE TITLE
POW/MAP2 Notifications Not Being Sent

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#118]
I recently submitted a few test jobs to POW and was surprised that the jobs completed normally, but I never received an email notifying me that the output was ready. Looking back at the POW/MAP2 job history, it appears that notification emails haven't been sent since at least 2 August 2018 (that's as far back as I can see in the history).

I'm not sure if we broke notifications in the PDS-Pipelines code at some point, or if we inadvertently removed an important line from crontab, or if the notifications were handled by a script outside of PDS-Pipelines that has moved, or something else.

**Comment by USGSsakins** [comment]
There are 4 cron jobs that are still running as pds2010mgr from taskmaster (the old Moab cluster head node), the notify job was commented out, I've un-commented it but these functions need to be migrated to the new Python code base and the cron jobs moved to nebula:

`10 * * * * /opt/common/cluster_processing/pds2010mgr/pds/bin/wrapper_notify.csh`
`0 5 * * * /opt/common/cluster_processing/pds2010mgr/pds/bin/wrapper_PURGE.csh`
`0 4 * * * /opt/common/cluster_processing/pds2010mgr/pds/bin/wrapper_PURGE_MAP.csh`
`0 6 * * * /opt/common/cluster_processing/pds2010mgr/pds/bin/wrapper_2dayB4_PURGE.csh`

**Comment by dpmayerUSGS** [comment]
Something has changed on `taskmaster` that is preventing the old cronjobs from running correctly. Issue #123 contains more details on the scripts themselves and proposes that they be ported to Python.

**Comment by thareUSGS** [comment]
If possible, I would like to bump up this priority. I think many jobs are not getting picked up since no one is notified.

**Comment by thareUSGS** [comment]
👍 Tested outside - Thanks for getting this working again.
