### ISSUE TITLE
Ingestqueueing.py: Add "--verbose" option

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#120]
`Ingestqueueing.py` currently sends log output to a file, but it would be useful to have a `--verbose` commandline option that would print messages to both STDOUT and the log file while also printing additional information that may not be currently captured by the default logging.

In particular, `verbose` should cause the script to print information including
- [ ] "Successfully connected to server xyz" (or not)
- [x] Added xx files to the Redis queue
- [x] The name and location of the log file that it's writing to (useful for debugging config problems)
- [x] Warnings and errors (i.e. "can't find volume /path/to/vol/searched/", "Can't connect to file system," "can't connect to server xyz"

**Comment by AustinSanders** [comment]
In lieu of "connected to server..." the script logs the queues to which items will be added.
