### ISSUE TITLE
Need to track and control how many processes use NFS share

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#128]
The POW/MAP2/DI processes all use the /pds_san/ NFS share.  Too many concurrent jobs can overload the NFS server and cause slowdowns in processing.  Therefore we need a way to coordinate the different processing jobs and manage how many cluster jobs we are creating which rely on the NFS mount.  This could be done with a Redis queue or through another mechanism.

**Comment by dpmayerUSGS** [comment]
@USGSsakins Is this something that we're still pursuing?
My understanding is that we've figured out how to monitor the load on the NFS but I'm not sure how to turn that into something practical for PDS-Pipelines. We could probably make something that would prevent a PDS operation from running until the load fell below a certain threshold, but many users have access to the SAN (not just PDS-Pipelines), so there wouldn't be a mechanism to enforce a fair level of access among all users.
