### ISSUE TITLE
Set up Sphinx for code documentation

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#129]
Now that we have added documentation to many of the files and methods in the PDS Pipelines, we need to set up a way to generate documentation from these.  Sphinx recognizes the tags we have used and is a likely first thing to try.  Info on Sphinx can be found at http://www.sphinx-doc.org/en/1.6/index.html.  Also, the following folder in another Astro repo uses Sphinx for documentation: https://github.com/USGS-Astrogeology/datasetws/tree/master/sphinx

**Comment by AustinSanders** [comment]
@eabovre What is the status of this ticket?  I know that you put a considerable amount of effort into this -- can it be considered complete?

**Comment by eabovre** [comment]
@AustinSanders I am pretty sure we can consider this complete. I saw you pulled the gh-pages branch onto your fork. As far as I know its good to go, its been a little while since I looked at this. I know if you go to https://AustinSanders.github.io/PDS-Pipelines/ the docs are all up there.
