### ISSUE TITLE
Exit condition bug in DIprocess.py

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#142]
A recent DI run using the latest version of master exited with the following error:
```
Traceback (most recent call last):
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/DIprocess.py", line 94, in <module>
    sys.exit(main())
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/DIprocess.py", line 52, in main
    item = literal_eval(RQ.QueueGet().decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'

```

The DI ready queue is empty and the DI log doesn't show any errors with commits. I'm wondering if we have a bug in how DIprocess.py does the commits on the last <49 items in the queue?

UPDATE: Annette started another DI job before I was able to send out a stop work request. I asked her to clear the DI ready queue after the job had started. DI ran on a few hundred files and then exited normally after it saw that the queue was empty. I'm not sure what this means other than we haven't been able to reproduce the error yet...

**Comment by asunda99** [comment]
I ran FindDI_Ready.py on all volumes process in the last DI job, roughly half of each volume was skipped in the DI Process.

lro_lroc_edr   Vol | Initial Files | Remaining Files
LROLRC_0001 | 106,521 | 53310
LROLRC_0002 | 152,573 | 76287
LROLRC_0003 | 71,354 | 35676
LROLRC_0004 | 194,684 | 97342
LROLRC_0005 | 208,577 | 104289
LROLRC_0006 | 199,521 | 99760
LROLRC_0007 | 230,277 | 115139
LROLRC_0008 | 249,191 | 124596
LROLRC_0009 | 245,009 | 122504
LROLRC_0010 | 245,009 | 106813
LROLRC_0011 | 245,009 | 116724
LROLRC_0012 | 218,553 | 109277
LROLRC_0013 | 225,843 | 112921
LROLRC_0014 | 212,466 | 106233
LROLRC_0015 | 209,391 | 104696
LROLRC_0016 | 207,525 | 103762
LROLRC_0017 | 195,063 | 97532
LROLRC_0018 | 208,728 | 104364
LROLRC_0019 | 197,973 | 98987

**Comment by AustinSanders** [comment]
When I refactored the code, I apparently forgot to remove one of the original processing steps, so there were two QueueGet() calls.  This popped two items off for every one item processed, so half of them didn't get processed.  This is addressed in PR #
