### ISSUE TITLE
Non-FIFO Behavior of DI Processing

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#151]
After I had to interrupt a DI job yesterday by clearing out the DI_ReadyQueue, @asunda99 noticed that the 10 LROC volumes that had been queued for DI had each been partially-DI'd. This suggests 

Nominally, volumes that are added to the DI queue should be processed in FIFO order. This helps with both the human bookeeping, and maintaining the required 30-day cadence of running DI.

We need to determine whether `DIprocess.py` is reading from the queue in FIFO order or not. If it's not, that should be treated as a bug, and fixed. If it *is* pulling from the queue in FIFO order, there may be an issue with how the queue is being constructed in the first place.

**Comment by AustinSanders** [comment]
The RedisQueue class is written as more of a RedisStack, which confirms and explains the FILO behavior we see here.  When pushing to the "queue" we're using rpush.  When popping from the queue, we're using rpop.  This should be as simple as changing from rpop to lpop, i.e. "pop from the front, push to the back".

**Comment by dpmayerUSGS** [comment]
#152 fixes this in dev. Let's just keep this issue open until the changes have been merged into master.

**Comment by AustinSanders** [comment]
#152 Resolves this issue and was PRd to master as of #155
