### ISSUE TITLE
Run jobs on slurm

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#17]
Can the pipeline framework schedule jobs on our current processing cluster running slurm?  If not, is there a way for us to use the existing PDS-Pipelines code for creating slurm jobs to add this capability?  How much work is involved if we do that?

**Comment by dpmayerUSGS** [comment]
Closing this old issue. PDS-Pipelines is capable of generating SBATCH scripts and submitting jobs to SLURM via `hpc_job_manager.py`
