### ISSUE TITLE
Pipeline Backend DB Docker Container

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#18]
We will want a separate container for any database needed to support the pipeline framework so that this can be run independently (ie. on a different server potentially).  Dockerfiles for this should be stored in /services.

**Comment by AustinSanders** [comment]
Dockerfiles + docker-compose.yml are stored in .containers.  At time of writing, we have dockerfiles for postgres and geoserver.
