### ISSUE TITLE
change output default to GeoTiff in the POW interface

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines#189]
With the change over from Kakadu to OpenJPEG (in GDAL) we should play it safe for a while and change the default output format to GeoTiff (from Jpeg2000). The Tiff will not be nicely compressed (but it will be in the zip file).

**Comment by dpmayerUSGS** [comment]
@USGSsakins  took care of this while also dropping GeoJPEG2000 support from the web front end.
