### ISSUE TITLE
Create a Docker container with postgres / pgadmin

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#196]
Create a docker container with postgres / pgadmin.
This should use Docker Secrets in order to avoid publishing database credentials.

**Comment by jlaura** [comment]
https://github.com/USGS-Astrogeology/autocnet_server/blob/master/services/docker-compose.yml

In case that saves you a few steps.

**Comment by AustinSanders** [comment]
Implemented in db_refactor branch
