### ISSUE TITLE
Add a model that describes the default SearchTerms table

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#197]
Add a model 'SearchTerms' to upc_models.py with the following columns:

- upcid (integer)
- starttime (time)
- solarlongitude (float)
- meangroundresolution (float)
- phaseangle (float)
- incidenceangle (float)
- emissionangle (float)
- boundingboxintersactions (float)
- targetid (integer)
- instrumentid (integer)
- missionid (integer)
- pdsproductid (integer)

**Comment by USGSsakins** [comment]
Do we need another model for the table storing the JSON keywords column?  This column is likely to be fairly large and we don't necessarily want to slow down the response of the SearchTerms table by including it.

**Comment by AustinSanders** [comment]
In order to allow for #199, the column names in the model must exactly match the names of keywords in the KeywordsOBJ.

**Comment by AustinSanders** [comment]
As per meeting on 3/28, the table should include the following modifications:
- [ ] add UPC processing time
- [ ] add 'footprints' (Geometry)
- [ ] remove boundingboxintersections
- [ ] for phase / incidence / emission angle, add columns for max, min, and center.

**Comment by AustinSanders** [comment]
Implemented in db_refactor branch.
