### ISSUE TITLE
Select Python Pipeline Framework

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#20]
Evaluate the different Python pipeline frameworks.  One key feature we are looking for is to run the processes for the pipelines on our existing slurm processing cluster.  So either the framework needs to support this or we need to be able to add it in ourselves.

**Comment by AustinSanders** [comment]
As per the information provided above, my instinct is to go with [Airflow](http://bytepawn.com/luigi-airflow-pinball.html).
