### ISSUE TITLE
Refactor UPC_Processing error handling

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#201]
UPC_Processing error handling currently inputs some hard-coded values into Meta* tables.  If we're no longer using these tables, then this strategy is no longer suitable.

**Comment by USGSsakins** [comment]
What about putting the error information into a part of the JSON keywords column?

**Comment by AustinSanders** [comment]
Error information is being placed with bulk json.

Additional changes to be made:
- [ ] set err flag correctly in search terms table
- [ ] calculate and add checksum in JSON
- [ ] remove final references to MetaString and MetaBoolean

**Comment by AustinSanders** [comment]
Implemented in db_refactor branch.
