### ISSUE TITLE
Servicejobber.py: AttributeError in getMFileListWB()

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#204]
Trying to run Servicejobber.py under the PDS-Services conda environment yields the following:

```
/usgs/cdev/PDS-Pipelines/pds_pipelines/Servicejobber.py
Traceback (most recent call last):
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/Servicejobber.py", line 1019, in <module>
    sys.exit(main())
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/Servicejobber.py", line 664, in main
    fileList = xmlOBJ.getMFileListWB()
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/Servicejobber.py", line 531, in getMFileListWB
    Mfile = info.find('.//internalpath').text
AttributeError: 'NoneType' object has no attribute 'text'
```

I'm not sure what `internalpath` is in this context or why it might be None. There were several jobs waiting in the queue before I ran Servicejobber.py, so I don't think this error represents an edge case of not having something to process.

**Comment by dpmayerUSGS** [comment]
I can't seem to reproduce this. May have been a fluke while I was switching between old and new POW/MAP2 code earlier today.
May close if I still can't reproduce it after further testing.

**Comment by AustinSanders** [comment]
Closing on the grounds that this error cannot be reproduced.  If more information is made available, we may choose to reopen this issue.
