### ISSUE TITLE
POWprocess.py and MAPprocess.py: pysis can't find ISIS programs

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#208]
The process scripts fail with an error from pysis that it can't find whichever ISIS program is being called. This occurs even when I manually export `$ISISROOT` and run `source $ISISROOT/scripts/isis3Startup.sh` before running `Servicejobber.py`

This may be an issue with how pysis looks for ISIS rather than an issue with how we define $ISISROOT.

**Comment by dpmayerUSGS** [comment]
I did some more digging and determined that this error results from a limitation in how `pysis` extracts information about the ISIS. `pysis.env` is correctly identifying `ISISROOT` but is failing to correctly parse the ISIS version number from `$ISISROOT/version` because it can only handle version numbers of the form `x.x.x`, but the particular version of ISIS that we are trying to run is listed as `3.5.2.0`, so `from pysis import isis` fails.

This is a recent change in behavior for `pysis` that makes it more consistent with the move towards semantic versioning of ISIS (see https://github.com/USGS-Astrogeology/ISIS3/issues/684).

The solution is to run POW/MAP2 on a newer version of ISIS.

**Comment by dpmayerUSGS** [comment]
Apparently this isn't as simple as pointing to a newer version of ISIS in our environment: https://github.com/wtolson/pysis/issues/23

**Comment by jlaura** [comment]
https://github.com/USGS-Astrogeology/pysis

@Kelvinrr fixed this and @wtolson merged. You might need to manually install or force reinstall to get the newest version. Alternatively, you might need a manual install if the version number was not incremented on the merge.  If the latter is the case, I am sure that @wtolson would appreciate a PR.

**Comment by dpmayerUSGS** [comment]
@jlaura The merged fix from @Kelvinrr only addressed issues with ISIS_ROOT and how the ISIS version number is parsed. 
The issue I reported has to do with ISIS_PATH, which is different. The latest master of pysis still sets ISIS_PATH assuming `bin` is immediately below ISIS_ROOT:
https://github.com/USGS-Astrogeology/pysis/blob/master/pysis/env.py#L51
https://github.com/wtolson/pysis/blob/master/pysis/env.py#L51

Am I missing something?

**Comment by dpmayerUSGS** [comment]
Oops!
Solution is actually to change how `$ISISROOT` is defined if using versions >=3.6.
Beginning with 3.6.0, `$ISISROOT` for internal (USGS) users should be set to `/your/path/install` rather than `/your/path/isis`.
Thanks @Kelvinrr for helping me figure this out!
