### ISSUE TITLE
A Python Script to Monitor NFS Mounts

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#213]
We need a way to verify if our NFS mounts are still working for POW/MAP2 or if they have lost their connection and turned into a "stale file handle".  To do this, the Python script needs to:

- [x] Accept a file path on the command line (ie. use getargs)
- [x] Accept one or more e-mail addresses from the command line
- [x] If the file exists, exit without any output or e-mails
- [x] If the file is missing, send an e-mail to a list of e-mail addresses hard coded into the script

This tool will be run automatically from a cron job.

**Comment by eabovre** [comment]
Should I put this script in the "tools" folder?

**Comment by USGSsakins** [comment]
@eabovre The tools folder sounds like a good place.

**Comment by AustinSanders** [comment]
Included in PR #241
