### ISSUE TITLE
Create a script that will clear timestamps for specified POW/MAP2 jobs

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#219]
In order to better facilitate testing, we need a script that clears timestamp information from records associated with a given processing key.

Usage:
./clear_timestamps.py -k jobkey

Expected outcome:
All timestamp information (queued, submitted, started, finished, accessed, notified, purged) for the record associated with jobkey should be set to None.

**Comment by AustinSanders** [comment]
@dpmayerUSGS @USGSsakins This is finished, but I'm not sure that we need it anymore.  Should I push this to a different branch or just close the issue?

**Comment by dpmayerUSGS** [comment]
@AustinSanders I would like to see this in the tools directory on "master"
