### ISSUE TITLE
Servicejobber.py: Add option to make SBATCH file, but don't run it

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#220]
In order to make it easier to test run POW and MAP2 jobs, we should add an option to `Servicejobber.py` that will process a key and do everything that Servicejobber currently does, *except* issue the `HPCjob.Run()` command at the end.

This should have the effect of setting up the FileQueue and writing an SBATCH file to disk, but not actually kicking off the job in SLURM. We can then potentially modify the SLURM job parameters for testing purposes before triggering the SLURM job "manually."

**Comment by AustinSanders** [comment]
Are we planning to make a new script, or is this something that could be done by issuing a "--dry" flag (or similar) to servicejobber?

**Comment by dpmayerUSGS** [comment]
@AustinSanders just a command line flag. I'm not sure I want to call it `--dry` because that implies that nothing happens, when if fact we want to do everything *except* actually run the SBATCH file that is created.

Maybe `--no-hpc`?  `--no-run`?
