### ISSUE TITLE
Need to decode job key for logging

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#232]
It looks like we aren't decoding the jobkey everywhere in `POWprocess.py`. The script fails immediately with the following error output:
```
Traceback (most recent call last):
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/POWprocess.py", line 351, in <module>
    sys.exit(main())
  File "/usgs/cdev/PDS-Pipelines/pds_pipelines/POWprocess.py", line 72, in main
    logger = logging.getLogger(key + '.' + basename)
TypeError: must be str, not bytes
```

**Comment by AustinSanders** [comment]
I ran into this right as I was leaving on Tuesday.  I was able to fix + test it for POW processing, but I didn't get a chance to push.  I also need to make the necessary changes for MAP, but this should be a quick and easy fix.

**Comment by AustinSanders** [comment]
To clarify, this is not an issue with the jobkey, it is an issue with the basename.  Basename is derived from jobFile, which is the result of a call to Qfile2Qwork in the RedisQueue.
