### ISSUE TITLE
POW interface: stretch quirk 

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines#24]
From outside user, there is a workflow where unsetting "stretch" doesn't work.

1>      Select images and go to the ‘submit a job’ form
2>      Select a recent job in the template options. Make sure it was using a 32bit isis cub as the output format.
3>      Fill in pixel size
4>      Submit the job
5>      Note that you get this error (see image)  -- "Download File Format -- 2 Errors"

![image](https://user-images.githubusercontent.com/3095138/39455201-1b711480-4c94-11e8-87fc-c2fd36516853.png)

Now, If you click the signed, 16bit radio button, you will see this (see image)  -- "Min/Max Stretch need to be between 0 and 100"

![image](https://user-images.githubusercontent.com/3095138/39455207-21c1d090-4c94-11e8-9dd5-ef0b321c895e.png)

Lastly, even if the percent stretch box is unchecked, and the format is 32bit, it will still show that there is an error and not allow you to submit the job.

**Comment by thareUSGS** [comment]
For the last error, anytime the user selects "Floating Point, 32 Bit", the stretch should be turned offed by default (although they can check it back on), which is correctly happening, **and** the original Min/Max Stretch errors should be removed such that the job can be now submitted. 

For POW, when the user checks "Byte, 8 Bit" or "Signed, 16 Bit" we should set the defaults back 0.5 and 99.5 (if they have been cleared by the user). If there are values there, they can be kept.

**Comment by AustinSanders** [comment]
@thareUSGS Is this something that should be posted in the issues for POW/MAP2, or is this something that can be fixed on the pipelines side?

**Comment by thareUSGS** [comment]
This is for the POW front-end. You're correct this is porbalby not the right place for this. We don't have a github site for the interface code - do we?

**Comment by AustinSanders** [comment]
@thareUSGS If I remember correctly, the POW/MAP2 code was managed with subversion.  I may be thinking of something else - but I'm not aware of any git repo for POW/MAP2 interface code.

**Comment by AustinSanders** [comment]
@USGSsakins @thareUSGS I'm in the process of cleaning the 'issues' board, and this is something that falls outside the scope of the PDS-Pipelines library.  Should we create a separate repo for front-end issues and migrate these issues?

**Comment by thareUSGS** [comment]
👍 a front-end repo is probably best.
