### ISSUE TITLE
UPC Instruments table populated by UPC processing

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#244]
In the past, the instruments table was populated from a config file.  It would be more manageable to have the instruments table populated by processing from the header information of the files added to an instance of the UPC database.

**Comment by AustinSanders** [comment]
One field to be manually populated: DisplayName

DisplayName is a human-readable version of the instrument name.

**Comment by AustinSanders** [comment]
Resolved in #250
