### ISSUE TITLE
Specify what database instance to process UPC into

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#246]
There need to be options to control what instance of the UPC database is to be populated.

- [ ] Is it a custom instance for none PDS released data being used for a project?
- [ ] Do we always want an instance per target body, or do we want to be able to control where the data goes?

**Comment by AustinSanders** [comment]
@USGSsakins How does this differ from using the configuration file to specify a database?  Are we just looking for an on-the-fly specification/configuration that can be used without editing config.py?

**Comment by AustinSanders** [comment]
Should be implemented as a command line argument that allows for a path and instance specification.  Should default to whatever is specified in the config file.

**Comment by AustinSanders** [comment]
@USGSsakins @dpmayerUSGS @jlaura  Given that our benchmarks for the refactored database have lead us to pursue a single database instance, is this issue still relevant?

There's still the possibility that someone will create their own unique database instance, but it seems to me that that case is handled by the default database specification in the config file.

**Comment by USGSsakins** [comment]
@AustinSanders I agree this issue is no longer relevant and the ad hoc instances can be handled with the config file.
