### ISSUE TITLE
Log "File Not Found" Errors to a Redis Queue

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#254]
As a person monitoring the running of DI and other services, if a file is missing and a file not found error is reported this error should go to a log file and be added to a Redis queue so that these errors can be displayed from a web dashboard for monitoring services.

**Comment by AustinSanders** [comment]
@USGSsakins Is this something that should be implemented on the refactor branch, or should I branch from master?

If we need this functionality soon, it may be worth branching from master and PRing back to master.  This means, though, that when we eventually merge the db_refactor branch back in, we'll probably have to edit the UPC-related scripts to get this functionality back.

If this is something that can wait, it might be worth just adding to the db_refactor branch and getting the functionality when we merge branches.

**Comment by USGSsakins** [comment]
@AustinSanders This is totally something that can wait and is not a high priority, I just opened the issue so we didn't forget about it.
