### ISSUE TITLE
UPC: Better Support for Parallel Processing

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#257]
The current workflow for UPC involves processing files in series. It would be much more efficient to process files in parallel, kind of like how POW works. This would require first copying files into `/scratch` so we don't overload the NFS, and then setting up an array job in SLURM to process many images in parallel.

To implement this, I propose the following:
- [x] `UPCqueueing.py` should *copy* files from specified archive and volume into the workarea defined in `config.py` before populating UPCReadyQueue
- [x] For archives that used detached labels, `UPCqueueing.py` must copy both the labels and the image data into the workarea. 
- [x] The logic that handles copying of files from the archive into the work area must have some sort of safety built in to prevent it from filling up the work area's file system
  - Compare total size of requested files to space available in work area
  - Safety margin? I.e., do not allow a copy that will total >`x`% of the free space left in work area for some value of `x`
- [x] Modify `UPC_process.py` to only process the first image it finds in the UPCReadyQueue, rather than looping over all entries in the queue
- [x] Use the existing `--jobarray` option in `HPCjobber.py` to set up the size of the array when executing UPC
  - This should be aware of the maximum array size allowed by a particular install of SLURM (`scontrol show config | grep -E 'MaxArraySize'`) in order to prevent a user from submitting an array that is too large (which will prevent it from running)
 - [x] Implement a "cleanup" flag to indicate whether files should be deleted after UPC processing, or left in the workarea for subsequent use by processes such as thumbnail/browse. A default value for the cleanup flag should be set in the config file.
 - [x] Messages to output logs need to be prefaced with SLURM Job ID and Array Task ID, or have the curent log functions write to STDERR and STDOUT, so that the messages will in effect be captured by SLURM.

It may also be advantageous to chain UPC processing to browse/thumbnail processing by having `UPC_process.py` populate the thumbnail/browse queues upon successful processing of an image, although this raises some questions about how to effect file cleanup in the workarea.

**Comment by AustinSanders** [comment]
Closed in #310
