### ISSUE TITLE
Error or warning from SQLAlchemy trying to create existing tables

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#262]
When running UPCprocess.py, the follow errors/warning are showing up in the Process.log:

2019-07-26 11:46:38,795 - UPC_Process - ERROR, Unable to create 
SearchTerms table: (psycopg2.ProgrammingError) relation "search_terms" 
already exists

It looks like SQLAlchemy is trying to create the tables even though they already exist.  Maybe a check for whether the table has already been built needs to be added.

**Comment by AustinSanders** [comment]
@USGSsakins Is this using the latest version of the db_refactor branch?  d0cc1a3 should have removed all the table creation functionality from upc_process.

I just grep'd the command used to create tables, and it appears be used only within the init_db script and IngestProcess.  The call within IngestProcess should actually be removed, but it's not related to this issue.

**Comment by dpmayerUSGS** [comment]
@AustinSanders I just grep'd `UPC_process.py` in our testing area and it appears to still have all the table creation logic in it. I'm not sure how that happened because we cloned it on 12 July and that commit went in on 5 July.

I will fetch the latest db-refactor branch into our testing area, run another test and report back.

**Comment by dpmayerUSGS** [comment]
@AustinSanders Mystery solved! The commit went in on 5 July, but wasn't merged until 18 July. We didn't fetch the latest version before running the test on 26 July, so of course the version of `UPC_process.py` in our testing area still had the table creation logic in it.

Juts operator error, not actually a bug.
