### ISSUE TITLE
UPC_process.py: Is find_keyword duplicated?

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#287]
This block of code/function may be present in the same state from another file, verify this is needed or reduce to a single instance of this function

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L38

**Comment by AustinSanders** [comment]
Closed in #310
