### ISSUE TITLE
UPC_process.py: Put error queue name in config

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#289]
The name of the Redis error queue should be in the config.py, this would allow for all programs to write to the same queue with a simple change if we want that model in the future.

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L121

**Comment by AustinSanders** [comment]
Closed in #310
