### ISSUE TITLE
UPC_process.py: Move print statements to debug logging

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#290]
Some output statements should write to the "debug" level logging:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L148

**Comment by USGSsakins** [comment]
Add debug statement for:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L151

**Comment by USGSsakins** [comment]
This should write to the "error" level log:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L223

**Comment by AustinSanders** [comment]
Closed in #310
