### ISSUE TITLE
UPC_process.py: Read paths and URL defaults from config.py

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#291]
The SAN path and URLs need to be read from the config.py for ease of maintenance as things "move" across servers:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L151-L153

**Comment by AustinSanders** [comment]
Closed in #310
