### ISSUE TITLE
UPC_process.py: Status string fixes

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#292]
There are 2 issues with how the `status` variable is set and referenced

- [x] Remove this unnecessary "reset" https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L210
- [x] Since we set the string ourselves the same everytime, we don't need to call `.lower()`

**Comment by AustinSanders** [comment]
It may be worth revisiting the removal of "lower."  Some other functions (like AddProcessDB) return "SUCCESS" and "ERROR."  It'd be easy to change these to lower case, but we'll need to track them down and see how/if they're being used.

**Comment by AustinSanders** [comment]
Closed in #310
