### ISSUE TITLE
UPC_process.py: Add inline comment for "fix" on labels

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#293]
This block of code needs a short comment explaining why we are doing regex fixes on the labels:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L233-L242

**Comment by AustinSanders** [comment]
Closed in #310
