### ISSUE TITLE
UPC_process.py: Need to lookup `datafiles` entries by edrsource

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#295]
Need to look for existing `datafiles` rows by the edrsource field

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L270-L279

If the record is found, overwrite existing values in case anything has changed with new processing.

**Comment by AustinSanders** [comment]
Closed in #310
