### ISSUE TITLE
UPC_process.py: Look up for instruments needs to include spacecraft

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#296]
When looking up the DB entry for an instrument, we need to use both the instrument name (instrumentid) and the spacecraft since many spacecraft has instruments called "NAC" that were different instruments.

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L258-L263

**Comment by USGSsakins** [comment]
And here in the error handling block

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L368-L372

**Comment by USGSsakins** [comment]
And here:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L408-L412

**Comment by AustinSanders** [comment]
@USGSsakins @dpmayerUSGS 

I'm convinced that the error handling code doesn't even run properly. The nested list structure should be associated with the PVL from caminfo.  If we're in the error block, then caminfo either didn't run or wasn't run successfully, so we should just be reading the pds label, and pds labels are mostly flat.

If that's the case, then we should be looking for 
```upc_models.Instruments.instrument == str(label['INSTRUMENT_ID']) ```
... right?

I'm confused as to why we're not getting key errors here.

**Comment by AustinSanders** [comment]
Closed in #310
