### ISSUE TITLE
UPC_process.py: Remove call out for band list

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#298]
With the new database schema, there is no longer a table specifically for the list of bands for an image.  This block of code is therefore no longer needed.

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L289-L300

And these blocks setting up variables for the above redundant code:
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L213-L214
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L219-L220

**Comment by AustinSanders** [comment]
Closed in #310
