### ISSUE TITLE
UPC_process.py: If a searchterm keyword is missing, set to null

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#299]
When getting the keywords from the label for the searchterms table, if there is a missing keyword, set the searchterm column to `null`

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L309

**Comment by AustinSanders** [comment]
Closed in #310
