### ISSUE TITLE
EPIC: Script Documentation

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/PDS-Pipelines#3]
This is an epic that will spawn a number of tickets to track progress.  The `.py` files are light on function level documentation.  I would like to get documentation in in [numpy style](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). 

We should generate a ticket for each of .py file and add an associated documentation label to help track these.

**Comment by eabovre** [comment]
I am pretty sure I have finished this with the knowledge I currently have. Should I keep this issue open, or go ahead and close it?

**Comment by jlaura** [comment]
:+1: Go ahead and close.  Congrats!
