### ISSUE TITLE
UPC_process.py: Should we keep intermediate files?

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#300]
Should some of the intermediate files from UPC_process.py be kept for generating browse, thumbnail, and map projected products?  Should this be done with a command line argument?

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L344-L345

**Comment by USGSsakins** [comment]
And here:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L449

**Comment by AustinSanders** [comment]
Closed in #310
