### ISSUE TITLE
UPC_process.py: Error block does not create instrument/target if new entry

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#301]
The error processing tries to look up target and instrument info from the DB, but does not have the logic from above to create these DB entries if this is the first time we are dealing with an instrument or target.

Should the logic to do this be moved to a function so it is the same for the main branch and error case?

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L364-L372

**Comment by USGSsakins** [comment]
Right now it is handled with an "exit":

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L414-L415

**Comment by AustinSanders** [comment]
Closed in #310
