### ISSUE TITLE
UPC_process.py: Remove "fake" geometries for errors

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#302]
The lines setting the center point and footprint for errors is no longer needed with the new database schema.  Remove these lines:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L390-L391

**Comment by AustinSanders** [comment]
Closed in #310
