### ISSUE TITLE
UPC_process.py: Log why the error block exception was called

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#305]
If there was a problem writing/creating the error entry, the `catch` should write a log message to `warn`:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L438-L439

**Comment by AustinSanders** [comment]
Closed in #310
