### ISSUE TITLE
UPC_process.py: Final log message?

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#307]
The final logging message of the UPC_process.py should be updated.  Take out the "success" part and if available include the `edrsource` variable:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L457

**Comment by AustinSanders** [comment]
@USGSsakins As part of the changes made for #257, all applicable log entries will include the inputfile as part of their default format.  Do we want to include EDRsource here as well, or is inputfile enough?

**Comment by AustinSanders** [comment]
Closed in #310
