### ISSUE TITLE
HPCjobber.py: Pass Commandline Options to Process Scripts

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#309]
**Description**
`HPCjobber.py` is used to build and execute .sbatch scripts that wrap various PDS processes, such as Ingest, DI, and UPC. The python scripts that get wrapped may have their own commandline arguments, but there currently isn't a convenient way to pass those arguments to the process script from `HPCjobber.py`.

For example, `IngestProcess.py` has an optional argument, `--override` that allows it to re-ingest files that already exist in the DI database. In order to enable this option from `HPCjobber.py`, the user must enter `--process ingest-override` as opposed to `--process ingest`, which runs the ingest script without the override option. This requires maintaining separate entries on `jobconfig.py` for `ingest` and `ingest-override.` These entries are identical *except* that the latter includes the `--override` option.

It would be much simpler to be able to run `HPCjobber.py --process ingest --override` and have the override option appended to the line in `HPCjobber.py` that builds the actual command being wrapped by the .sbatch script:
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/HPCjobber.py#L77

**Proposed Solution**
Support for passing options on to the wrapped scripts can be accomplished by adding an optional positional parameter into `HPCjobber.py`'s argument parser with `nargs=argparse.REMAINDER`
Docs here:
https://docs.python.org/3.6/library/argparse.html?highlight=REMAINDER#nargs

**Definition of Done**
 - [x] add optional argument to `HPCjobber.py` (perhaps called `process-args`) with `nargs=argparse.REMAINDER`
 - [x] append list of any remainder argguments to the command being wrapped by `HPCjobber.py`
 - [x] remove `ingest-override` process from `jobconfig.py`

**Comment by AustinSanders** [comment]
It turns out that "argparse.REMAINDER" doesn't offer much support for items prefixed with hyphens -- argparse think they're unspecified arguments.  Instead, we supplied the functionality by providing an additional "--args" flag.

Usage:

python HPCjobber.py --norun --process upc --args="--foo bar --test -f"

Note the equal sign and the quotes -- both of which are required.

**Comment by AustinSanders** [comment]
Closed in #310
