### ISSUE TITLE
UPC_process.py: Move recipeJSON inside of class

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#313]
The recipeJSON is being passed around as an argument, this should be changed to be a member variable of the class (https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/master/pds_pipelines/Recipe.py).

**Comment by kaitlyndlee** [comment]
@USGSsakins Are you referring to lines 235-240 in UPC_Process.py:
```
        # @TODO refactor this logic.  We're using an object to find a path, returning it,
        #  then passing it back to the object so that the object can use it.
        recipeOBJ = Recipe()
        recipe_json = recipeOBJ.getRecipeJSON(archive)
        #recipe_json = recipeOBJ.getRecipeJSON(getMission(str(inputfile)))
        recipeOBJ.AddJsonFile(recipe_json, 'upc')
```

**Comment by USGSsakins** [comment]
@kaitlyndlee This issue was created based on the comment @AustinSanders entered (included in your comment).  Please follow up with Austin on how he suggests we resolve this.  I think the original intention was to make the recipe_json a member variable of the recipeOBJ class.
