### ISSUE TITLE
Instrument band summary

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#336]
As a web developer, I need a listing of instruments and the bands that are included in the data for that instrument so that I can give users options for restricting their searches based on specific bands.

The band information for each image is stored in the JsonKeywords table.

The summary should include:
- [x] the instrument ID from the Instruments table
- [x] the instrument name
- [x] the filter name
- [x] the center wavelength value

**Comment by kaitlyndlee** [comment]
@USGSsakins Should we include the units for the center wavelengths?

**Comment by kaitlyndlee** [comment]
Query I have so far:

```
SELECT DISTINCT i.instrumentid, i.instrument, j.jsonkeywords -> 'caminfo' -> 'isislabel' -> 'isiscube' -> 'bandbin' ->> 'filtername' AS filtername, j.jsonkeywords -> 'caminfo' -> 'isislabel' -> 'isiscube' -> 'bandbin' -> 'center' ->> 0 AS center
FROM instruments i
JOIN json_keywords j on (j.jsonkeywords -> 'caminfo' -> 'isislabel' -> 'isiscube' -> 'instrument' ->> 'instrumentid' = i.instrument)
```

**Comment by kaitlyndlee** [comment]
Example output:
![image](https://user-images.githubusercontent.com/25512865/70940943-a3505700-2008-11ea-9657-bd73f2c2a7cb.png)

**Comment by USGSsakins** [comment]
@kaitlyndlee That looks good. Nice job!
