### ISSUE TITLE
Histogram summary of angle keyword values

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#337]
As a web developer, I need a histogram summary of angle keyword values for each instrument and target combination so that I can present summaries of available data to web site users.

- [x] Each bucket is 18 degrees (ie 0-18, 19-36, 37-54) for a total of 20 buckets
- [x] The keywords to track are maximum phase angle, minimum phase angle, maximum emission angle, minimum emission angle, maximum incidence angle, minimum incidence angle, and solar longitude
- [x] each summary line includes the target, instrument, the bucket range, the keyword, and how many images are in that bucket range

**Comment by USGSsakins** [comment]
Here is the SQL script from the old UPC schema for creating this summary:

```
DROP TABLE IF EXISTS new_histogram_degrees;
select d.instrumentid, d.targetid, m.typeid, 
width_bucket(m.value, 18, 360, 18) as bucket,
(width_bucket(m.value, 18, 360, 18)) * 18 || ' - ' || ((width_bucket(m.value, 18, 360, 18) + 1) * 18) || ' degrees' as range,
count(m.*) as total 
into new_histogram_degrees
from meta_precision m
join keywords k on (k.typeid=m.typeid)
join datafiles d on (d.upcid=m.upcid)
where k.typename in ('maximumphaseangle', 'minimumphaseangle', 'maximumemissionangle', 'minimumemissionangle',
                     'maximumincidenceangle', 'minimumincidenceangle', 'solarlongitude')
group by d.instrumentid, d.targetid, m.typeid, width_bucket(m.value, 18, 360, 18);
```

**Comment by AustinSanders** [comment]
@USGSsakins 

This is the SQL query that I have so far.  It separates instrument / target ids, but I couldn't get all that output in a screenshot.

The null values are the result of nulls in the original data, i.e. there are 16 products with NULL within maximumemission for instrument id = 1, target id = 1, 

```
DROP TABLE IF EXISTS new_histogram_degrees;

select s.instrumentid,
		s.targetid, s.stat_type,
		((width_bucket(s.val, 0 , 360, 20) -1) * 18) ||
		' - ' ||
		(width_bucket(s.val, 0 , 360, 20) * 18) ||
		' degrees' as bucket, count(*) as total
	
from (select t.instrumentid, t.targetid, v.* 
	  from search_terms t, 
	  LATERAL (values('solar_longitude', t.solarlongitude),
					  ('maximumphase', t.maximumphase),
					  ('minimumphase', t.minimumphase),
					  ('maximumemission', t.maximumemission),
					  ('minimumemission', t.minimumemission),
					  ('maximumincidence', t.maximumincidence),
					  ('minimumincidence', t.minimumincidence)) v (stat_type, val)) as s 
group by s.instrumentid, s.targetid, s.stat_type, bucket
order by s.instrumentid, s.targetid, s.stat_type;
```

![Screenshot from 2019-12-16 16-29-08](https://user-images.githubusercontent.com/3751180/70951705-59279f80-2021-11ea-9b00-9cf528267944.png)

I'm not sure if this satisfies the first requirement because it only generates buckets for which there are data. If there are no products with phase angle 0-18, then no bucket is created.  I'm not sure how to fix this.

**Comment by USGSsakins** [comment]
@AustinSanders What are the `[null]` rows for the bucket in the output?

**Comment by AustinSanders** [comment]
@USGSsakins The "null" buckets are buckets for which the incoming data are null.  The first row indicates that there are 16 entries that are missing their maximumemission field.

**Comment by AustinSanders** [comment]
It doesn't make sense to drop the new_histogram_degrees table since we're no longer selecting items into the table.  The updated query is: 

```
select s.instrumentid,
		s.targetid, s.stat_type,
		((width_bucket(s.val, 0 , 360, 20) -1) * 18) ||
		' - ' ||
		(width_bucket(s.val, 0 , 360, 20) * 18) ||
		' degrees' as bucket, count(*) as total
	
from (select t.instrumentid, t.targetid, v.* 
	  from search_terms t, 
	  LATERAL (values('solar_longitude', t.solarlongitude),
					  ('maximumphase', t.maximumphase),
					  ('minimumphase', t.minimumphase),
					  ('maximumemission', t.maximumemission),
					  ('minimumemission', t.minimumemission),
					  ('maximumincidence', t.maximumincidence),
					  ('minimumincidence', t.minimumincidence)) v (stat_type, val)) as s 
group by s.instrumentid, s.targetid, s.stat_type, bucket
order by s.instrumentid, s.targetid, s.stat_type;
```
