### ISSUE TITLE
Need summary of UPC holding volume

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#338]
As a web developer I need a summary by target and instrument of the UPC holdings to create navigation of available instruments to simplify end users' searches of the database.

The summary needs to include the following fields:
- [x] instrument ID from Instruments table
- [x] target ID from Targets table
- [x] target name from Targets table
- [x] system name from Targets table
- [x] instrument name from Instruments table
- [x] mission from Instruments table
- [x] spacecraft from Instruments table
- [x] display name from Instruments table
- [x] how many images are in the database for that instrument of that target
- [x] start date - the minimum value for the start time for images from that instrument on that target
- [x] stop date - the maximum value for the start time for images from that instrument on that target 
- [x] publish date - the maximum time stamp for UPC ingestion for images from that instrument on that target

**Comment by USGSsakins** [comment]
The SQL script to create this summary in the old UPC schema:

```
DROP TABLE IF EXISTS stats;
SELECT d.instrumentid, d.targetid, t.targetname, t.system, i.instrument, i.mission, i.spacecraft, i.displayname,
count(d.*) as image_count, min(m.value) as start_date, max(m.value) as stop_date, max(p.value) as last_published
INTO stats
FROM datafiles_w_footprints d,
targets_meta t,
instruments_meta i,
(select upcid, value from meta_time x, keywords y where 
x.typeid=y.typeid and y.typename='starttime') as m,
(select upcid, value from meta_time j, keywords w where 
j.typeid=w.typeid and w.typename='processdate') as p
WHERE t.targetid = d.targetid
AND i.instrumentid = d.instrumentid
AND m.upcid=d.upcid
AND d.upcid=p.upcid
GROUP BY d.instrumentid, i.instrument, i.mission, i.spacecraft, 
d.targetid, t.system, t.targetname, i.displayname
ORDER BY i.spacecraft, i.mission, i.displayname;
GRANT SELECT ON stats TO upcread;
```

**Comment by USGSsakins** [comment]
This query works for the new UPC schema (I am going to open an issue to add the process date to the search terms table for that column which is currently missing):

```
SELECT d.instrumentid, d.targetid, t.targetname, t.system, i.instrument, i.mission, i.spacecraft, i.displayname,
count(d.*) as image_count, min(s.starttime) as start_date, max(s.starttime) as stop_date
FROM datafiles d
JOIN instruments i on (i.instrumentid=d.instrumentid)
JOIN targets t on (t.targetid=d.targetid)
JOIN search_terms s on (d.upcid=s.upcid)
GROUP by d.instrumentid, i.instrument, i.mission, i.spacecraft, d.targetid, t.targetname, t.system, i.displayname;
```

**Comment by kaitlyndlee** [comment]
Output table as a JSON:
```
with query AS (
	SELECT d.instrumentid, d.targetid, t.targetname, t.system, i.instrument, i.mission, i.spacecraft, i.displayname,
	count(d.*) as image_count, min(s.starttime) as start_date, max(s.starttime) as stop_date, max(s.processdate) as publish_date
	FROM datafiles d
	JOIN instruments i on (i.instrumentid=d.instrumentid)
	JOIN targets t on (t.targetid=d.targetid)
	JOIN search_terms s on (d.upcid=s.upcid)
	GROUP by d.instrumentid, i.instrument, i.mission, i.spacecraft, d.targetid, t.targetname, t.system, i.displayname
)
SELECT json_agg(query) from query;
```

Good article: https://hashrocket.com/blog/posts/create-quick-json-data-dumps-from-postgresql
