### ISSUE TITLE
Need Process Date in search_terms table

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#340]
As a user of the UPC database I need the date an image was processed into the UPC database in the search_terms table so that I can quickly search for new data in the database being having to use the JSON keywords.

The upctime column needs to be renamed to processdate with a type of DATE.

**Comment by USGSsakins** [comment]
@AustinSanders is that what search_terms:upctime is?

**Comment by AustinSanders** [comment]
@USGSsakins @kaitlyndlee  Yes, search_terms:upctime captures the time at which a product was entered into the database
