### ISSUE TITLE
UPC Function Testing

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/PDS-Pipelines#351]
The  following functions need to be tested in UPC:
- [x] getPDSid
- [x] getISISid

**Comment by kaitlyndlee** [comment]
To what extent do we need to test these? Should we mock when getsn and getkey return? If not, then we are testing the pysis functions.

**Comment by acpaquette** [comment]
Yes, those two functions being used in getPDSid and getISISid should be mocked to return something as if they worked every time.
