### ISSUE TITLE
ingest_process uses old logic for UPC queueing

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#369]
IngestProcess queues the original file (from pds_san) using the old logic from upc_queueing.  The logic should either be updated or removed.  This leads to bugs / failures because UPC process is looking for products in the workarea.

I'd argue that the queueing functionality should be removed in order to provide a better separation of concerns (ingest_process only ingests).  The ability to queue the new volume is provided in upc_queueing, and that's where the logic should stay.

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#369](https://trello.com/c/NZNnE2X1/308-369)

**Comment by kaitlyndlee** [comment]
Is the only queue that needs to be removed from ingest_process.py is the RQ "RQ_work" created on line 56 of ingest_process.py?
