### ISSUE TITLE
upc_process.py: File naming/renaming logic is broken

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#374]
### Description ###
The current logic for naming input/output files and passing them to particular conditions inside the big if/elif/else block in `generate_isis_processes()` is broken. The function names the output of `*2isis` or `thmproc` as `outfile`, but then expects the input to functions that are run subsequently in the recipe (such as `spiceinit` or `footprintinit`) as `infile`. This prevents the functions from building a correctly-parameterized set of processes from a given recipe because the variables `infile` and `outfile` have different values. 

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/93d268bd0aec55057798d78c37068d958232a981/pds_pipelines/upc_process.py#L416-L467

#### Quick Fix ####
A short-term fix would be to just change the value of the "to" parameter in `*2isis` and `thmproc` to `infile`, redefine `infile` in the `handmos` case to have the same value as `thmproc_odd`, change the value of the "from" parameter in the `spiceinit`, `footprintinit`, and `caminfo` cases to `infile`, and remove the `cubeatt` case altogether. None of the recipes for high-priority datatsets (list in #281) actually *need* `cubeatt`, and it just complicates the logic in this block.

#### Long-term Solution ####
One way to make the function more general and robust to arbitrary recipes would be to implement a system of find/replace tokens in the recipe files (kind of like Jinja templates). This could eliminate the need for the if/elif/else block altogether, by allowing the individual recipes to guide the expected names of input/output files to each process. In practice, the only element of an input/output filename that can't be predicted in advance is the basename of the files. It should be possible for `upc_process.py` to insert the basename of a given product into the "to" or "from" value in a particular ISIS command, with the suffix defined within the recipe itself. This would render #325 moot.

Implementing this solution will require existing recipes to be edited/reformatted to be compatible with the templating system.

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#374](https://trello.com/c/JnBKjs35/266-374)
