### ISSUE TITLE
upc_process.py: Handle .QUB and .imq Files When Checking for Detached Labels

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#376]
### Description ###
`create_datafiles_record()` attempts to determine whether a given PDS file has an attached or detached label by parsing the value of the PDS3 pointer `^IMAGE`. If the value of the pointer is not an array, then the script infers that the product does not have a detached label. 
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/93d268bd0aec55057798d78c37068d958232a981/pds_pipelines/upc_process.py#L236-L238

However, certain PDS3 products, such as THEMIS spectral cubes and some legacy products that are stored in a compressed format (such as MOC EDRs) do not contain this pointer, which causes this function to raise a KeyError and the script errors out. 

### Proposed Solution ###
In practice, the types of PDS3 files that do not contain this pointer have attached labels. Thus, changing the exception condition to include both `TypeError` and `KeyError` should correctly identify files that do not contain `^IMAGE` has having attached labels.

Fixing this issue is a prerequisite for closing #281

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#374](https://trello.com/c/JnBKjs35/266-374)
