### ISSUE TITLE
AddProcessDB - Return Values

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/PDS-Pipelines#382]
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/master/pds_pipelines/upc_process.py#L76

The returns on this function are remarkably non-canonical. What about returning True/False or True/None maybe or 0/1? Alternatively, do not return anything since the caller (`main`) never even expects a return.

**Comment by AustinSanders** [comment]
AddProcessDB has been factored out of the system
