### ISSUE TITLE
AddProcessDB - Doc String

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/PDS-Pipelines#383]
It is not clear what the `outvalue` argument is in the [AddProcessDB](https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/master/pds_pipelines/upc_process.py#L76) method.

I see that `outvalue` is being passed to the DB model, but the model does not have a doc string. What is this argument? Right now, it is just being set to `True`.

**Comment by AustinSanders** [comment]
AddProcessDB (and its documentation) are no longer in use, and they have been removed from the system.
