### ISSUE TITLE
Decouple recipes/upc_process from pysis

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/PDS-Pipelines#392]
Step 1 for #248

Current all of the recipes and upc_process.py are coupled to only be able to run processing pipelines that use pysis, the ISIS python module. This directly conflicts with:
a. Build a generic recipe processing pipeline and
b. Generating level 2 (map projected) product entrees in the upc database

To account for this the current dev team working on upc processing has decided that going forward all recipes will be 
```
{
'module.function1': 
    {'arg1': 'arg1value', ... 'argN':'argNvalue'},
... 
'module.functionN': 
    {'arg1': 'arg1value', ... 'argN':'argNvalue'}
}
```
where the module will be something like `isis` or `gdal` and the `function` will be a function from the associated module. The change in the processing step will need to get the appropriate function from the module that is calling it by splitting on the . in `module.function` and getting the function from the module. Something like:
```
module, command = process.split('.')
func = getattr(module, command)
```

**Comment by jlaura** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for map projected (L2) data.](https://trello.com/c/aGh9fOSB/267-add-support-for-map-projected-l2-data)
