### ISSUE TITLE
Research/Test upc gdal support

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/PDS-Pipelines#399]
Given the recipe in #397 see what it will take to run the gdal commands using the gdal python module rather than the command line tools.

Ideally this will be a straight translation from command line arguments to function parameters but gdal in python tends to have a significant amount of boiler plate. 

Current solution/research: add "wrapped" gdal functions to the highest level init module and import/access them when needed.

**Comment by dpmayerUSGS** [comment]
Closed by #414
