### ISSUE TITLE
upc_process.py: Make glob pattern for removing files less greedy

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#436]
The glob pattern for removing files from the workarea directory is too greedy. This has the undesirable effect of deleting *all* files in the working directory, but some of those files may be part of UPC processing jobs running in parallel. 

The glob pattern should be made more specific to only remove files from the working directory that match the basename of `inputfile`. 

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/06ba9e3bf9c07f01d24914041cc8b159b741be1b/pds_pipelines/upc_process.py#L616

**Comment by acpaquette** [comment]
@dpmayerUSGS I don't know if there is a happy medium here. It seems that since we are using the base name for nearly all of the intermediate steps there is no clear way to define what is worth keeping. Unless we update the recipes to any file that we need to keep during intermediate steps gets some kind of flag.

**Comment by dpmayerUSGS** [comment]
@acpaquette If `--persist` is passed on the commandline, then the script doesn't attempt to delete anything, which is the desired behavior. This issue is really about what [*not*](https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/06ba9e3bf9c07f01d24914041cc8b159b741be1b/pds_pipelines/upc_process.py#L613) to keep when `--persist` is *not* passed on the commandline.

For example, let's say there is a working directory `workarea/foo/bar/ctx/mrox_1024/` and it contains 2 files that have been queued, `image_A.IMG` and `image_B.IMG`. In typical usage, `upc_process.py` is run as part of a SLURM array job, so both of those images get processed in parallel. Let's say that `image_A.IMG` gets finished processing first. With the current code, the entire contents of  `workarea/foo/bar/ctx/mrox_1024/` will get deleted even though there is a parallel task that is still working on processing `image_B.IMG`, which will cause the task for `image_B.IMG` to fail with an error, because either the .IMG or an intermediate cube will have been deleted. This is obviously undesirable.

Instead, if `--persist` is *not* passed on the commandline, and `image_A.IMG` finishes processing first, we would like `image_A*` to be deleted from the working directory, but anything else in the working directory gets left alone. 

What about the directories? Currently, upc_queueing.py faithfully reconstructs the directory structure of a queued archive inside `workarea/` (as defined by the config). If we only focused on deleting the files within a working (sub)directory, at the end of the job, we would be left with a hierarchy of empty directories. One way we could address this by having `upc_process.py` always check to see if the current directory (`mrox_1024/` in this example) of a file being worked on is empty *after deleting the files associated with that task*, and then working its way back up the tree checking for empty directories, and deleting them until `workarea/` is empty. 

We could potentially add a UPC_WorkQueue (kind of like how we have a *_WorkQueue for POW/MAP2) that holds entries from UPC_ReadyQueue that are *currently* being worked on, and check that it only contains 1 item (the current file) before recursively deleting directories. This would be an added safety measure to avoid deleting any files that are currently being processed.

I know that that sort of recursive deletion of directories has to be done with care.  If it seems too complex to tackle under this issue, I think it would acceptable as an interim solution to just delete the target files and leave the directories alone. A user (probably me) could come in after the fact and manually delete all the empty directories from `workarea/`.
