### ISSUE TITLE
PNG, Jpeg runs for MAP2 and I bet POW are not copying over worldfile or auxiliary sidecar files

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines#489]
Based on the results for this job,
https://astrocloud.wr.usgs.gov/index.php?view=viewjob&key=b3a0e5f5a18d9ff0d26e4f3dbf8a80bd

I am no longer seeing the geospatial side-car files as saved by gdal_translate for formats like Jpeg, PNG, ... This would be either a worldfile (*.jgw, *.pgw, *.gfw, *.wld), a GDAL auxiliary file (*.aux), or both. Since this are critical for GIS applications and they are small, they should be copied with the output images and *.map file (and available in the download zip).

**Comment by dpmayerUSGS** [comment]
It looks like what is happening here is that the axiliary file is not being renamed in `map_process.py` to match the basename of the final image file, and thus it's being missed when `service_final.py` goes to zip up the files and copy them to the download directory. Should be straightforward to fix.

By default, `gdal_translate` does not create worldfiles when writing JPEG, PNG, or GIF. If this is something that would be important to add, it should probably go under its own issue and be tagged as "enhancement." There are a few different ways that could be addressed.
