### ISSUE TITLE
derived_process.py: ISIS serial number unreliable for relating file to upcid

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#512]
## Description
When running `derived_process.py`, certain input files are matched to the wrong entry in the UPC database.

## Expected Behavior
Running `derived_process.py` should always match the input file to the correct entry in the UPC database

## Suspected Cause
`derived_process.py` computes the ISIS serial number of a given input file and then queries the DataFiles table in the UPC database for that serial number, and assumes that the upcid of the first result corresponds with the record for that file. However, ISIS serial numbers are not guaranteed to be unique within a dataset, so an input file may be matched to the wrong upcid.
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/391d7fab51c00a50b3b948e0313f13dc9767add0/pds_pipelines/derived_process.py#L96

## Additional Context
For *most* datasets, ISIS serial numbers ("isisid" in the UPC database schema) are unique within the dataset and therefore can be used to relate a particular file back to a upcid in the UPC database. However, they are *not* unique for files within archives including (but not limited to?) Clementine and Galileo SSI. In the case of Clementine (HiRES, NIR, or UVVIS), distinct images can have the same ISIS serial number. 

For example, [LHA1365J.328](https://pdsimage.wr.usgs.gov/Missions/Clementine/cl_0077/lun328/lhxxxxxx/lhxxxxxj/lha1365j.328) and [LHA1366J.328](https://pdsimage.wr.usgs.gov/Missions/Clementine/cl_0077/lun328/lhxxxxxx/lhxxxxxj/lha1366j.328) both yield the ISIS serial number "Clementine1/HIRES/1994-04-29T08:48:21.170" 

## Proposed Solution
The only thing that really makes a UPC record unique is the *path to the source file*. `derived_process.py` should compute the expected path to the source file based on file it is generated browse/thumbnail images for, and query the "source" column in the DataFiles table instead of the "isisid" column to try and fetch the upcid that corresponds to the input file.

**Comment by jlaura** [comment]
@dpmayerUSGS Can you open an issue on the ISIS repo or point me to a pair of images that result in the same serial number when using ISIS?

**Comment by dpmayerUSGS** [comment]
@jlaura Here is a pair of Clementine HiRes EDRs that yield the same serial number:

https://pdsimage.wr.usgs.gov/Missions/Clementine/cl_0077/lun328/lhxxxxxx/lhxxxxxj/lha1365j.328
https://pdsimage.wr.usgs.gov/Missions/Clementine/cl_0077/lun328/lhxxxxxx/lhxxxxxj/lha1366j.328

They both result in serial numbers of "Clementine1/HIRES/1994-04-29T08:48:21.170"

I don't really know what an issue on the ISIS repo should look like for this. There are several known reasons as to why products within a given archive may yield identical serial numbers. If you look at the labels for the above products, they appear to have the same value for `START_TIME` because the time stamps don't contain sufficient precision to distinguish images that were taken so close in time one after another, and the value of this keyword is used as part of the algorithm for generating a serial number. 

This kind of thing has been an issue since the beginning of ISIS serial numbers, but it's rare.
