### ISSUE TITLE
Shut down switch in Redis

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#52]
Using scancel to kill SLURM jobs can hang the database connections causing all following jobs to fail since they cannot get a valid database connection.  To send a signal to processes, we need to set a key in Redis letting the different jobs know it is okay to continue running, or that they should commit their current changes, close the database connections and exit.

- [x] Add Redis key (true/false) for each process type (ie. DI_Run, UPC_Run)
- [x] Add logic to the processing scripts (ie. DIprocess.py) to check this run key inside the while loop before collecting the next file from the Redis queue.  If the key is set to false, exit the while loop, clean up connections/files and exit safely
- [x] Provide a way to turn on and off process types from the command line

**Comment by AustinSanders** [comment]
Implemented in #154
