### ISSUE TITLE
Use Python's `hashlib` instead of using system calls in DIprocess

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#54]
Currently, the data integrity script uses the `subprocess` module to make system calls to `md5sum.`
We should consider refactoring to use Python's built-in `hashlib` module instead, thereby avoiding need to make system calls.

**Comment by USGSsakins** [comment]
We should verify the hashlib value is the same and then also change the md5sum call in the ingest process which sets the initial hash that is compared monthly to make sure the files haven't changed.

**Comment by dpmayerUSGS** [comment]
Agreed. We would obviously have to do some testing first. `hashlib` also doesn't work quite the same way as `md5sum.' We would have to write our own little loop that passes chunks of the file to the function a little at a time. We would want to do some testing to tune the block size to our hardware in order to maximize efficiency.

**Comment by AustinSanders** [comment]
@dpmayerUSGS @USGSsakins This (including chunking) is implemented in my latest pull request for all hashing -- not just in DIProcess.  At the moment, it's all performed inline -- in the future, it should  be pulled out into a separate function that exists in a util file.  Either way, it's only ~4-5 lines of code.

I've made sure that the generated checksums are the same as those stored in the db, but I haven't done any testing regarding the size of the chunks (chunk size if set to 4096 at the moment).  I'll leave the ticket open until we've done some fine-tuning, but I'm not really sure how to test this.

**Comment by dpmayerUSGS** [comment]
@AustinSanders Great! Could you please mention the PR # in this thread

**Comment by AustinSanders** [comment]
@dpmayerUSGS It's in #55.  Unfortunately, it's evolved into somewhat of a terrible blob PR with about 7 features rolled in ec5a5b2ff81fd460c581520378842c12a509cb06
