### ISSUE TITLE
upc_process.py: Speed up `pvl.load()` 

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#562]
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/f2b083a0d149dafd64a5a081a78d94f2409a5cc8/pds_pipelines/upc_process.py#L428

## Description ##
The `pvl.load()` function can take a long time (minutes to hours) to load the PDS label from large files with embedded labels, such as LROC NAC EDRs.  `upc_process.py` only needs to extract a few items from the label, so it's wasteful to have to wait for `pvl.load()` to scan through a potentially large image file to only load the relatively small label.

## Desired Behavior ##
The call to `pvl.load()` on the line above should only take as long as required to load the label as it would if the label were detached.

## Proposed Solution ##
Allow UPC recipes to include a call to the ISIS `catlab` program to dump PDS labels to a standalone PVL file, and then check for the existence of such a file within `upc_process.py`. If present, load the standalone PVL file, else load the original input file as the script currently does.

**Comment by Kelvinrr** [comment]
might be worth making an issue with the PVL library (https://github.com/planetarypy/pvl/), improving the performance of the that parser has been a want for a while. Especially since I do not think we can expect a python wrapped version of ISIS's PVL parser to be an independent library anytime soon which tends to be much more efficient.

**Comment by thareUSGS** [comment]
@dpmayerUSGS Might this be fixed by upgrading to the latest version of PVL? I think your solution is fine, but a fix PVL also sounds useful for many others.  And perhaps the latest version has addressed this (if not, perhaps a quick ticket).

**Comment by dpmayerUSGS** [comment]
I'm sure that PVL could be sped up, but I've also encountered some LROC images where `pvl.load()` just appears to hang. I suspect (but have yet to prove) this is because of something malformed in the label portion of the files that causes PVL to get confused. That's a data problem. The `catlab` workaround has handled all such cases that I'm aware of.

I will open an issue on the PVL library, but I'm really not sure what to say other than "make it faster." It's not really an issue with a closed form solution.

PDS-Pipelines is currently running pvl 1.2.0. The latest version available, 1.2.1, doesn't include any functional changes to the code, so updating would not make this issue go away.
