### ISSUE TITLE
JSON from old XML Configs

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/PDS-Pipelines#6]
We have XML files per instrument with the necessary commands.  We have definition and recipe files.  The definition keywords need to get pulled from the existing XML and pushed into the new JSON. 

The XML defines the type and keywords for each instrument. The database has common and instrument specific keywords in the database.  We need to be able to dynamically generate the JSON definition files from the database.

@USGSsakins will add information about how / what this entails.

**Comment by USGSsakins** [comment]
As an example of the XML config file from the old system, this file is for MRO CTX:

http://astrogit.wr.usgs.gov/dpmayer/upc-internal/blob/master/cluster_processing/archive/mro_ctx/config/config.xml

From this file, Bob created multiple recipe files, breaking out POW from UPC, etc.

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/master/recipe/POWrecipeCTX.json
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/master/recipe/test_UPCrecipeCTX.json

We need a way to:

- [ ] specify which XML config file to convert, ideally allowing a recursive wildcard to do a bunch at a time
- [ ] where to read from for those file (ie. the path)
- [ ] where to write the new JSON files

The program needs to:

1. Read in the XML file into a dict (look at using either https://pypi.python.org/pypi/xmljson or https://micropyramid.com/blog/how-to-convert-xml-content-into-json-using-xmltodict/)
2. Using a Jinja2 template to write out the new JSON files (http://jinja.pocoo.org/, JSON example https://gist.github.com/sevennineteen/4400462).

**Comment by USGSsakins** [comment]
When you are creating the Jinja2 templates for the POW and UPC JSON files, if you see where the same content is being done in both files.  We may want to combine the files into 1 rather than having to maintain the same thing in 2 places.

**Comment by eabovre** [comment]
I have a python environment up and running. Where can I find the XML files that I will be converting?

**Comment by thareUSGS** [comment]
See the links from Scott's thread above. The config.xml for CTX is a good start.

**Comment by AustinSanders** [comment]
An initial conversion tool is included in pr #72. It is not yet as 'general purpose' as I'd like it to be in terms of its applicability to multiple instruments.  The processes included in many recipes are not found within the same location among xml files, are missing entirely, or are duplicated in the xml, which makes it difficult to make this a truly general purpose tool.

In any case, the tool appears to be working well for mroctx and is able to reproduce the manually specified JSON recipe with the exception of information that cannot be found in the xml (cam2map, ctxevenodd).

I'll continue to add pieces to the tool, but I think that it'll end up being a tool that gets a "pretty close recipe" that needs some manual tailoring based on domain expertise that I don't have.
