### ISSUE TITLE
Optimize database file search

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#60]
## Issue:
  On multiple occasions, the pipeline uses fuzzy matching on filename (using the 'like' operator) to find information about a file in the database.  This would be much better implemented using the fileid.

## Preliminary testing:
  Despite the fact that the files table includes an index on filename, finding a file based on fuzzy string matching took an average of 176 ms in a table with ~750,000 rows.  The same search based on fileid took an average of 13 ms.

As the tables grow, fuzzy matching scales significantly worse.
Fuzzy matching on the upc_prd database (~28 million rows) took 11.1 seconds
Fileid based search took 14 ms.

## Proposal:
  Find a way to use the fileid for searches instead of fuzzy matching.  This could potentially be orchestrated using the redis queue to store a tuple of (filename, fileid) instead of storing only the filename.

**Comment by USGSsakins** [comment]
the redis queue with a tuple of filename and fileid sounds like a good plan. thanks for identifying this issue @AustinSanders
