### ISSUE TITLE
Additional geometry information in UPC

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines#61]
Brent has requested for an image, run we should add in the 
(1) the shape model that was used for image projection (per image).
(2) geometry source information (SPICE file names, per image)

**Comment by USGSsakins** [comment]
I think we already capture the SPICE kernel in the keywords. The shape model for the projection will be harder since the keywords are calculated separately from the projected image processing

**Comment by dpmayerUSGS** [comment]
We currently capture the type of CK and SPK kernels (i.e. "Reconstructed"), but not the names of the kernels themselves. This should be an easy thing to start capturing.

**Comment by AustinSanders** [comment]
@dpmayerUSGS Is this closable given that we capture the entire list of keywords in the JSONB column?

**Comment by dpmayerUSGS** [comment]
@AustinSanders Yes.
