### ISSUE TITLE
Remove old files for POW and MAP2

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#69]
When a processing job for POW or MAP2 is 2 weeks past the date when the 'notified' flag was set, the files should be removed from the /pds_san/PDS_Services and /scratch areas and the 'purged' timestamp set in the jobs database.  This process will be run through cron or another scheduling system on a nightly basis.

**Comment by AustinSanders** [comment]
@USGSsakins Which database/table contains the 'notified' flag?  I was referencing #62 when I created the initial rm_expired_pow script, and I didn't realize that it should be using information from a database.  It's currently just referencing mtime from sys.stat() and deleting anything that was last updated > 2 weeks ago.
