### ISSUE TITLE
Converting old config.xml to Recipes for UPC/Thumbnail/Browse/Projected

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#70]
The previous version of UPC processing used a single config.xml file to specify the sequence of commands for processing an instrument to get the keywords for the database and to create thumbnail and browse images.  In the current version, Bob had created separate JSON files to capture this same information.  The separate JSON files are for the UPC, thumbnail, browse, and a projected image.  In converting the XML to JSON, it may not make sense to separate these files.

This issue is to convert the XML for use by the process tools (UPCprocess.py, thumbnail_process.py, browse_process.py, and projectionbrowse_process.py) either as separate JSON files or in a combined recipe file.

If the JSON files are combined into a single recipe file, refactor the different process scripts to read the subsection of the recipe file relevant to that processing.

**Comment by AustinSanders** [comment]
JSON recipes are available as of #73.
