### ISSUE TITLE
Check for necessary resources on a node/platform

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#71]
There are file systems, databases and Redis queues which are necessary for different _process.py's to be able to complete their processing.  We need a way to check this that is consistent (ie. single code base) across the scripts, but allows for checking the specific resources needed by that process.py.

The check needs to be able to:
- [ ] check for a file system on the node/platform
- [ ] verify write access to the file system
- [ ] check database connections are working (ie. run a query and get a result)
- [ ] check that Redis queues are accessible

If any of these fail, the module needs to set an error or some kind of notification that includes:
- [ ] what resources wasn't available (ie. no file system, couldn't read from DB, etc.)
- [ ] what platform this was running on (ie. which Slurm node or AirFlow worker)

**Comment by dpmayerUSGS** [comment]
@USGSsakins Is this adequately addressed by #241 ?
