### ISSUE TITLE
Create an environment.yml

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/PDS-Pipelines#9]
Going through each `py` file, we want to know what the external dependencies for this are.  Then we can use those inside of a setup.py (or conda recipe).  Once we have a listing of the external dependencies as a response to this issue we can create an environment.yml and get the pipelines into conda/virtual environments.

**Comment by eabovre** [comment]
I am pretty sure these are the only dependencies that are not native to python or defined in the PDS-Pipelines scripts. What are the next steps to take?

pvl
xml
lxml
shutil
pysis
pytz
sqlalchemy
config
redis
squalchemy
geoalchemy2
pdb

**Comment by jlaura** [comment]
@AustinSanders Can you review this and confirm or deny?

**Comment by AustinSanders** [comment]
@jlaura Looks good.  I wasn't able to find any missing dependencies.

**Comment by AustinSanders** [comment]
@eabovre check [here](https://github.com/USGS-Astrogeology/PySAT/blob/master/environment.yml) for an example environment.yml file

**Comment by jlaura** [comment]
@AustinSanders :+1: Thanks!
@eabovre With that example, I would create an environment.yml file and commit it to the repo.  Then we can close this ticket and open another one to see if we can create a conda env that sequesters all of Bob's code. This will make the project portable as the environment will be reproducible.
