### ISSUE TITLE
CTX - UPC Processing

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#91]
End to end processing of UPC eligible CTX images populating the internal production database (dino)

- [x] Verify keys/values for https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/dev/pds_pipelines/PDSinfo.json
- [x] Verify recipe.json steps are correct for the instrument
- [x] Capturing Keywords
- [x] Adding to the database
- [x] Ready to sync to DMZ searchable databases

**Comment by AustinSanders** [comment]
@USGSsakins @dpmayerUSGS What does it mean to be ready to sync to dmz searchable databases? I.e. what is the definition of "ready" in this context?

**Comment by USGSsakins** [comment]
@AustinSanders For the data to be "ready" to sync to the DMZ you need to have gone through a sampling of the entries you have created in the internal production database (ie. dino) and verified the keywords are all being created correctly from the image and are populated in the internal production database so that the data is "ready" to be synchronized to the external (ie. DMZ) databases for searching in pilot and other tools.

**Comment by AustinSanders** [comment]
mro_ctx has been tested and appears to be ready for sync.  Because some of the artifacts have already been upc processed (and already exist in the db), they're being updated rather than rewritten.  This means that the mostly newly processed items do not necessarily have the highest upcid, and we should search based on processing date.

UPCID 25817 was used to verify readiness to sync.

**Comment by AustinSanders** [comment]
Refactoring the logic such that a keyword definition file is no longer used caused there to be a discrepancy in the names of 'common' keywords in the database and in the labels.  It may now be necessary to create a mapping between these names or to change the keywords in the database to reflect what is in the labels.

Until these changes are made, the 'common' keywords will not found/entered in the database.

**Comment by AustinSanders** [comment]
Tested on production database with upcid 10055521.  All expected keywords are present with the exception of "ctxid," which is missing due to its classification as a "meta_integer" when it should be a string.  The 'ctxid' keyword is also missing in pilot, so it has probably never worked.
