### ISSUE TITLE
THEMIS-IR - UPC

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#92]
End to end processing of UPC eligible THEMIS-IR images populating the internal production database (dino)

- [x] Validate configuration .json
- [x] Capturing Keywords
- [x] Verify recipe.json steps are correct for the instrument
- [x] Adding to the database
- [x] Ready to sync to DMZ searchable databases

**Comment by AustinSanders** [comment]
Tested on production database with upcid = 18547517

All expected keywords are present except 'exposureduration' and 'partialsumlines.'

'exposureduration' is a common keyword that is missing in favor of the instrument-specific 'imageduration.'

'partialsumlines' is of type 'meta_integer,' but gets a value of 'n/a,' which we elected to ignore.
