### ISSUE TITLE
HiRISE EDR UPC Processing

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#93]
End to end processing of UPC eligible HiRISE EDR images populating the internal production database (dino)

- [x] Verify keys/values for https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/dev/pds_pipelines/PDSinfo.json
- [x] Verify recipe.json steps are correct for the instrument
- [x] Capturing Keywords
- [x] Adding to the database
- [x] Ready to sync to DMZ searchable databases

**Comment by AustinSanders** [comment]
Tested in production database with upcid = 11143781

All keywords present in pilot were properly captured.
